language: scala
dist: trusty
matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    scala: 2.10.6
  - env: SBT_VERSION="1.0.2"
    scala: 2.12.10

script:
  - ./.travis.sh

notifications:
  email:
    recipients:
      - andy@sudostream.io

jdk:
  - openjdk8
